---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mysql56::default]
    attributes:
